Update stacks node configuration
blockstack/docs pull request #1004
Opened 2021-01-03 21:07 UTC by friedger

## Description

There are a few configuration properties of the stack node that are not described.

This PR adds missing properties and descriptions.

@agraebe

2021-01-03 21:12 UTC, friedger commented
I just added the missing properties and would need some help to add the correct descriptions and examples.

2021-01-04 14:10 UTC, CharlieC3 requested changes
Thanks for adding these! I know this is a WIP and you were probably planning on making the below changes soon. Feel free to check them off as you go.

2021-01-04 14:10 UTC, CharlieC3 commented on src/pages/references/stacks-node-configuration.md
> +List of nodes that must not be added to neighbors
Comma-separated or space-separated list?

2021-01-04 14:10 UTC, CharlieC3 commented on src/pages/references/stacks-node-configuration.md
> +deny_nodes = ???
Let's change the example to something closer to what the user might want to use.
```suggestion
deny_nodes = 1.2.3.4,exclude.this.node.org
```

2021-01-04 14:10 UTC, CharlieC3 commented on src/pages/references/stacks-node-configuration.md
> +#### microblock_frequency (optional)
Needs description and example to match document format.

2021-01-04 14:10 UTC, CharlieC3 commented on src/pages/references/stacks-node-configuration.md
> +#### max_microblocks (optional)
Needs description and example to match document format.

2021-01-04 14:10 UTC, CharlieC3 commented on src/pages/references/stacks-node-configuration.md
> +#### pox_sync_sample_secs (optional)
Needs description and example to match document format.

2021-01-26 22:13 UTC, agraebe commented
@friedger @CharlieC3 what is the next step on this PR?

2021-01-28 18:08 UTC, CharlieC3 commented
> what is the next step on this PR?

@agraebe Should be good to merge once the above comments are addressed. I'd add them myself if @friedger doesn't have the resources, but I don't know what the properties do.

2021-02-01 21:52 UTC, agraebe commented
@friedger could you please take a look?

2021-03-08 23:11 UTC, agraebe commented
closing due to inactivity. please reopen if/when you get a chance. thanks!

2021-03-08 23:11 UTC, closed without merging