[WIP] nft onboarding
blockstack/docs pull request #1143
Opened 2021-04-29 14:28 UTC by agraebe

2021-05-20 13:51 UTC, jdbender66 commented on src/pages/write-smart-contracts/tokens.md
> +into the ecosystem. Under the [SIP-009][] standard, fungible tokens must have the following characteristics:
I believe this link should go to SIP-010 instead of SIP-009?

2021-06-16 01:27 UTC, agraebe commented
note: we should add docs for the new NFT API endpoint

2021-06-21 15:45 UTC, pgray-hiro requested changes
Some minor changes in the language used here. Otherwise looks good. I've tried to capture my recommendations into our budding style guide.

2021-07-09 22:32 UTC, agraebe commented on src/pages/write-smart-contracts/nft.md
> +``get-last-token-id` and `get-token-uri` functions of the contract.
one ` too much

2021-07-09 22:33 UTC, agraebe commented on src/pages/write-smart-contracts/nft.md
> +code editor on the **Write & Deploy** page. Edit the contract name or use the randomly generated name provided to you.
we can link to this view directly now

2021-07-09 22:34 UTC, agraebe reviewed
looks good to me! left a few minor suggestions

2021-07-09 22:34 UTC, agraebe commented on src/pages/write-smart-contracts/nft.md
> +When your contract is confirmed, navigate to the **Call a contract** page of the sandbox, and search for your contract.
we can also link to this view directly

2021-07-15 21:16 UTC, pgray-hiro approved these changes

2021-07-15 21:21 UTC, closed without merging