Update clarinet installation method
blockstack/docs pull request #1225
Opened 2021-06-28 11:27 UTC by friedger

## Description
This PR removes the description how to install clarinet because it fails:
```
cargo install clarinet --locked
    Updating crates.io index
error: could not find `clarinet` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
```

## Checklist

- [x] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] New links to files and images were verified
- [x] For fixes/refactors: all existing references were identified and replaced
- [x] [Style guide](https://developers.google.com/style) was reviewed and applied
- [x] Clear code samples were provided
- [x] People were tagged for review @agraebe

2021-06-28 14:08 UTC, CharlieC3 commented
Here's a question for @lgalabru: Should `clarinet` be uploaded to Crates.io upon release? Technically I don't think it would pose an issue, but it doesn't sound like it fits the use case Rust maintainers [have laid out here](https://rust-cli.github.io/book/tutorial/packaging.html#when-to-use-it).

2021-06-29 01:24 UTC, pgray-hiro requested changes
Minor changes to improve links for screen readers.

2021-06-29 01:24 UTC, pgray-hiro commented on src/pages/write-smart-contracts/clarinet.md
> +try installing it from source code as described [here](https://github.com/hirosystems/clarinet#install-from-source-using-cargo).
```suggestion
try [installing it from source code](https://github.com/hirosystems/clarinet#install-from-source-using-cargo).
```

2021-06-29 01:24 UTC, pgray-hiro commented on src/pages/write-smart-contracts/clarinet.md
> +You can download a release from [github/hirosystems/clarinet](https://github.com/hirosystems/clarinet/releases/latest) or
```suggestion
You can download a release from the [Clarinet repository](https://github.com/hirosystems/clarinet/releases/latest) or 
```

2021-07-01 14:01 UTC, pgray-hiro commented
Closes #1208

2021-07-01 14:01 UTC, pgray-hiro approved these changes

2021-07-01 14:19 UTC, merged