fix: docs for connect-react
blockstack/docs pull request #764
Opened 2020-09-03 21:52 UTC by hstove

Small docs changes for Connect usage in React apps.

Changes:
- You need to import from `@blockstack/connect-react` to use hooks and the provider
- Removed the note about bundle sizes, since React is no longer included

2020-09-04 15:29 UTC, aulneau requested changes

2020-09-04 15:29 UTC, aulneau commented on src/pages/authentication/connect.md
> +If you're using `connect` in a React app, then the best option is to use the package `@blockstack/connect-react`, utilizing React Provider and hooks in your React app.
We should explicitly say `[React Context Provider](https://reactjs.org/docs/context.html)`

2020-09-04 15:29 UTC, aulneau commented on src/pages/authentication/connect.md
> +First, setup the `Connect` provider at the "top-level" of your app - probably next to wherever you would put a Redux provider, for example.
again, preface provider with `context`

2020-09-04 15:29 UTC, aulneau commented on src/pages/authentication/connect.md
> +  finished: ({ userSession }) => {
We should use the new `onFinish` callback

2020-09-08 13:45 UTC, agraebe approved these changes
LGTM

2020-09-08 13:48 UTC, agraebe commented
can you include updates from https://github.com/blockstack/docs/pull/762 in your PR as well?

2020-09-22 15:13 UTC, hstove commented
Waiting to merge this until https://github.com/blockstack/ux/pull/582 is released.

2020-11-02 22:17 UTC, agraebe approved these changes

2020-11-02 22:18 UTC, merged