docs: update mining docs
blockstack/docs pull request #799
Opened 2020-09-28 20:45 UTC by agraebe

2020-09-28 20:47 UTC, lgalabru approved these changes
LGTM

2020-09-28 21:03 UTC, aulneau requested changes

2020-09-28 21:03 UTC, aulneau commented on src/pages/mining.md
> +Make sure you've followed the [Running testnet node](https://docs.blockstack.org/stacks-blockchain/running-testnet-node) tutorial. Once completed it's only a few more steps to run a proof-of-burn min
make sure to not do absolute urls when they are internal links. This causes a full page reload instead of a client-side navigation.

2020-09-28 21:03 UTC, aulneau commented on src/pages/mining.md
> +!> Make sure to complete the first
First what?

2020-10-01 00:28 UTC, agraebe commented
@aulneau please have another look

2020-10-01 17:20 UTC, merged