feat: add stacks-gen
blockstack/docs pull request #801
Opened 2020-10-01 00:45 UTC by psq

This adds a reference to [stacks-gen](https://github.com/psq/stacks-gen) to the accounts creation page

2020-10-01 01:51 UTC, agraebe approved these changes
LGTM, thanks @psq

2020-10-01 15:16 UTC, aulneau requested changes

2020-10-02 00:04 UTC, psq commented on src/pages/stacks-blockchain/accounts.md
> +npx -q stacks-gen sk --testnet
@aulneau I did not include it as this was not included on the mining page either: https://github.com/blockstack/docs/blob/70fad9f0e5072eb41fb4ca7a6ba8c6c3eed735bf/src/pages/mining.md#L28\

As someone who really does not like to install things globally, I find npx more suitable.  I'll add explanations on how to get `npx` installed.

2020-10-02 00:11 UTC, psq commented on src/pages/stacks-blockchain/accounts.md
> +npx -q stacks-gen sk --testnet
addressed by c6596f9

2020-10-02 01:04 UTC, aulneau commented on src/pages/stacks-blockchain/accounts.md
> +npx -q stacks-gen sk --testnet
Can you link to npx so folks can learn more about it? I use it too, but there are risks as it runs any arbitrary code immediately, and some people might not prefer that.

2020-10-02 01:12 UTC, psq commented on src/pages/stacks-blockchain/accounts.md
> +npx -q stacks-gen sk --testnet
added a link and a small blurb in 68b8ece32dbbadb150730cfc676d51a7d81716b9

2020-10-06 00:47 UTC, psq commented on src/pages/stacks-blockchain/accounts.md
> +npx -q stacks-gen sk --testnet
@aulneau could you check whether my latest change addresses your comment?

2020-10-06 01:05 UTC, aulneau approved these changes

2020-10-06 01:23 UTC, psq commented
note: I don't have merge access, so someone will need to merge that in... Thanks!

2020-10-06 23:28 UTC, merged