changes to incorporate Proof of Transfer
blockstack/docs pull request #845
Opened 2020-11-01 20:46 UTC by joshmatix

**Added new files file:**
pages/pox/overview.md
public/images/pox.png

**Changes to existing files:**

next.config.js
async function redirects() {
  return [
    {
      source: '/pox/overview.html',
      destination: '/pox/overview',
      permanent: true,
    },
	

navigation.yaml
- title: Technology
    pages:
      - path: /pox
        pages:
          - path: /overview
		  
		  
		  
pages/index.md
[@page-reference | grid-small]
| /ecosystem/overview, /ecosystem/stacks-token, /stacks-blockchain/running-testnet-node, /pox/overview

2020-11-02 20:00 UTC, agraebe requested changes
thanks for the PR @joshmatix 🙏 I left some comments, most importantly the nav structure request

2020-11-03 21:59 UTC, agraebe commented on src/common/navigation.yaml
> +#      - path: /pox
let's remove this comment, assuming it's a leftover from before. with that, we should be good to go

2020-11-03 22:00 UTC, agraebe commented on src/pages/index.md
> +| /ecosystem/overview, /ecosystem/stacks-token, /stacks-blockchain/running-testnet-node, /pox/overview
shouldn't `/pox/overview` > `/stacks-blockchain/pox`?

2020-11-04 15:17 UTC, agraebe approved these changes

2020-11-04 16:59 UTC, agraebe commented
I resolved a conflict and previewed the changes in gitpod. A few suggestions:

- for the image inside the markdown, we should prefer the markdown style for images: `![<alt>](<src>)`
- leaving the file named as `pox.md` will create `Pox` navigation item, which we should avoid. I'd suggest we rename the file to `proof-of-transfer.md` and update the references
- the markdown file should end with an empty new line. I'd run a linter and fix to ensure we account for every linting rule
- @jasperjansz - I'm marking this for you to review. I think this illustration needs to be updated (can happen after we merge this PR)

2020-11-05 00:19 UTC, agraebe approved these changes

2020-11-05 04:27 UTC, joshmatix commented
Since it is approved, do I have to do anything else to this PR?

2020-11-05 18:39 UTC, agraebe commented
thanks @joshmatix, we can merge it now but I seem not to be able to trigger that action.

@aulneau - do you have the same issue? merging is disabled due to lack of check completion?

2020-11-09 18:37 UTC, agraebe commented
@joshmatix it turns out I can't merge this PR because of a conflict. could you resolve/rebase so we can merge this asap? thanks!

2020-11-09 18:45 UTC, joshmatix commented
Will rebasing fix the following error:

Run aulneau/vercel-action@v20.0.0
/home/runner/work/_actions/aulneau/vercel-action/v20.0.0/dist/index.js:6801
throw new Error(`Input required and not supplied: ${name}`);
^
Error: Input required and not supplied: vercel-token
at Object.getInput
(/home/runner/work/_actions/aulneau/vercel-action/v20.0.0/dist/index.js:6801:15)

at Object.104
(/home/runner/work/_actions/aulneau/vercel-action/v20.0.0/dist/index.js:1052:26)

at __webpack_require__
(/home/runner/work/_actions/aulneau/vercel-action/v20.0.0/dist/index.js:22:30)

at startup
(/home/runner/work/_actions/aulneau/vercel-action/v20.0.0/dist/index.js:37:19)

at
/home/runner/work/_actions/aulneau/vercel-action/v20.0.0/dist/index.js:41:18

at Object.<anonymous>
(/home/runner/work/_actions/aulneau/vercel-action/v20.0.0/dist/index.js:44:10)

at Module._compile (internal/modules/cjs/loader.js:959:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
at Module.load (internal/modules/cjs/loader.js:815:32)
at Function.Module._load (internal/modules/cjs/loader.js:727:14)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Mon, Nov 9, 2020 at 1:37 PM Alexander Graebe <notifications@github.com>
wrote:

> @joshmatix <https://github.com/joshmatix> it turns out I can't merge this
> PR because of a conflict. could you resolve/rebase so we can merge this
> asap? thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/blockstack/docs/pull/845#issuecomment-724198668>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADTSJICSFVCEFBZDR4QQDTSPAZHZANCNFSM4TGXVKUQ>
> .
>

2020-11-09 18:57 UTC, aulneau commented
The vercel action will never work in this PR due to it's origin is a fork. If you rebase from `master`, we can test out the deployment via the official vercel github addon.

2020-11-09 19:06 UTC, joshmatix reviewed
added to vercel

2020-11-09 19:59 UTC, joshmatix commented
I followed the instructions under
https://docs.blockstack.org/ecosystem/contributing#working-locally

Do those instructions have to be updated?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Mon, Nov 9, 2020 at 1:57 PM Thomas Osmonson <notifications@github.com>
wrote:

> The vercel action will never work in this PR due to its origin is a fork.
> If you rebase from master, we can test out the deployment via the
> official vercel github addon.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/blockstack/docs/pull/845#issuecomment-724210096>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADTSJLEVWO2BUECUOGPHE3SPA3TLANCNFSM4TGXVKUQ>
> .
>

2020-11-09 20:30 UTC, agraebe commented
@joshmatix I'll merge this PR as part of https://github.com/blockstack/docs/pull/897

thanks for the contribution!

2020-11-09 20:30 UTC, closed without merging